### ISSUE TITLE
add in simple cherrypy example

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/project-templates#1]

**Comment by sonadztux** [comment]
What should I do, mate?

**Comment by verhulstm** [comment]
Cool, thanks. So last night at https://www.meetup.com/OpenTeams/ we decided to post some Hacktoberfest issues. For this repo we are collecting good, working, and simple demonstrations. For this issue we want a simple cherrypi demo. use python version 3.6  and include a requirements file. The demo should send a simple "hello world" to the browser and receive text form input and print that to the terminal.

**Comment by verhulstm** [comment]
https://cherrypy.org/

**Comment by verhulstm** [comment]
we would also like other PRs that are simple working code demos. Basically any languages. This is used as a learning tool at https://github.com/Jacob-Barhak/EveningOfPythonCoding

**Comment by sonadztux** [comment]
Ah i see. Well, I will try to work on it and make a PR.

**Comment by verhulstm** [comment]
thanks
